packaging_format = 2

id = "pinry"
name = "Pinry"
description.en = "Pinry is a sharing picture application, grouping everything together in boards."
description.fr = "Pinry est une application de partage de photo à la manière de pinterest, elle regroupe tout à travers des boards."

version = "1.0~ynh1"

maintainers = ["johndoe"]

[upstream]
license = " BSD 2"
website = "https://docs.getpinry.com/"
demo = "https://pin.37soloist.com/"
# admindoc = "https://yunohost.org/packaging_apps"    # TODO > Not set
# userdoc = "https://yunohost.org/apps"               # TODO > Not set
code = "https://github.com/pinry/pinry"
# FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, YunoHost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
# cpe = "???"
# FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.
# fund = "???" Nothing to support this app

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = false                              # TODO > No idea about this settings
ldap = false                                        # The app can't support this feature
sso = false                                         # Not sure, it's to force a login with the SSO ?
disk = "50M"                                        # TODO > Not set
ram.build = "50M"                                   # TODO > Not set
ram.runtime = "50M"                                 # TODO > Not set

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pinry"

    [install.init_main_permission]
    type = "group"
    default = "visitors"


[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/pinry/pinry/archive/refs/tags/v2.1.12.tar.gz"
        sha256 = "B80590EACAA6C4D872D09AF97E3904BF074D1AD25EE8EC3F69DD0D2C827EE63E"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    # packages = "deb1, deb2, php8.0-foo, php8.0-bar"

    # [resources.database]
    # This will automatically provision/deprovison a MySQL DB and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    # type = "mysql"
